version: '3.9'

services:
  web:
    build:
      context: .
      args:
        WEB_PORT: ${WEB_PORT}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    command: ["sh", "-c", "sh /app/migrate.sh && uvicorn app.main:app --host 0.0.0.0 --port 8100"]
    networks:
      - default  
  db:
    image: postgres
    environment:
       - POSTGRES_PASSWORD=${DB_PASSWORD}
       - POSTGRES_DB=${DB_NAME} 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PUBLIC_PORT}:5432"
    networks:
      - default 

networks:
  default:
    name: naryn_track

volumes:
  postgres_data:
    driver: local

